fullNameOverride: ""
nameOverride: ""

# Deployment.

extraDeploymentLabels: {}
deploymentAnnotations: {}

replicas: 1

# Pod.

extraPodLabels: {}
podAnnotations: {}

affinity: {}
imagePullSecrets: []
nodeSelector: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
tolerations: []

# Container.

resources: {}
securityContext: {}

image:
  repository: "ghcr.io/evolutics/comkube"
  pullPolicy: IfNotPresent

env:
  - name: RUST_LOG
    value: info

# Role-based access control (RBAC).

rbac:
  create: true

  extraClusterRoleLabels: {}
  clusterRoleAnnotations: {}

  extraClusterRoleBindingLabels: {}
  clusterRoleBindingAnnotations: {}

# Service account.

serviceAccount:
  create: true

  name: ""
  extraLabels: {}
  annotations: {}
