# NOTE: Keep this in sync with `values.schema.json`.

# TODO: Consider name override.

# Deployment.

extraDeploymentLabels: {}
deploymentAnnotations: {}

replicas: 1

# Pod.

extraPodLabels: {}
podAnnotations: {}

affinity: {}
imagePullSecrets: []
nodeSelector: {}
podSecurityContext: {}
tolerations: []

# Container.

resources: {}
securityContext: {}

image:
  repository: ghcr.io/evolutics/comkube
  pullPolicy: IfNotPresent

# Role-based access control (RBAC).

rbac:
  create: true

  extraClusterRoleLabels: {}
  clusterRoleAnnotations: {}

  extraClusterRoleBindingLabels: {}
  clusterRoleBindingAnnotations: {}

# Service account.

serviceAccount:
  create: true

  name: ""
  extraLabels: {}
  annotations: {}
