apiVersion: v1
kind: ServiceAccount
metadata:
  name: comkube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: comkube
subjects:
  - kind: ServiceAccount
    name: comkube
    namespace: default
roleRef: # TODO: Use fine-grained role instead.
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comkube
spec:
  selector:
    matchLabels:
      app: comkube
  template:
    metadata:
      labels:
        app: comkube
    spec:
      serviceAccountName: comkube
      containers:
        - name: comkube
          image: ghcr.io/evolutics/comkube
