apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapgenerators.evolutics.info
spec:
  group: evolutics.info
  scope: Namespaced
  names:
    plural: configmapgenerators
    singular: configmapgenerator
    kind: ConfigMapGenerator
    shortNames:
      - cmg
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                content:
                  type: string
