apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: composeapps.evolutics.info
spec:
  group: evolutics.info
  scope: Namespaced
  names:
    plural: composeapps
    singular: composeapp
    kind: ComposeApp
    shortNames:
      - compose
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
