apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet
  annotations:
    kompose.version: 1.37.0 (HEAD)
spec:
  template:
    metadata:
      annotations:
        kompose.version: 1.37.0 (HEAD)
