apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: comkube
subjects:
  - kind: ServiceAccount
    name: comkube
    namespace: default
roleRef: # TODO: Use fine-grained role instead.
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
