apiVersion: apps/v1
kind: Deployment
metadata:
  name: comkube
spec:
  selector:
    matchLabels:
      app: comkube
  template:
    metadata:
      labels:
        app: comkube
    spec:
      serviceAccountName: comkube
      containers:
        - name: comkube
          image: ghcr.io/evolutics/comkube
          env:
            - name: RUST_LOG
              value: info,kube=debug,comkube=trace
